Iniciando o projeto e criando cadastro de cliente com validação de CEP
devJoseOtavio/voandoComAsaas pull request #3
Opened 2022-03-29 17:27 UTC by devJoseOtavio

Realizei a criação da página de cadastro do cliente onde fiz uma validação de CEP através de js

![miniAsaas](https://user-images.githubusercontent.com/101358660/160843196-e9209da4-5ab1-4f27-b638-0a95bf033820.gif)

2022-03-31 16:25 UTC, geanfarias commented on bin/main/index.gsp
> +    <title>AsaasCadastro</title>
a maioria dessa informação já está no main.gsp, não precisa repetir aqui

2022-03-31 16:28 UTC, geanfarias commented on grails-app/assets/javascripts/miniAsaasJs/miniAsaas.js
> +document.getElementById('cepCliente').addEventListener('focusout', getCep);
por que não "blur"?

2022-03-31 16:53 UTC, devJoseOtavio commented on grails-app/assets/javascripts/miniAsaasJs/miniAsaas.js
> +document.getElementById('cepCliente').addEventListener('focusout', getCep);
Conseguimos utilizar os dois, o blur utilizamos ao clicar na tecla "tab" e escorregar as informações para os próximos campos, no caso seria os valores do endereço a partir do CEP,  resolvi utilizar o focusout pois ele também funciona como o blur e ainda com adicional de ao clicar em qualquer outra coisa já passar as informações do CEP, não dependendo da tecla.

2022-03-31 16:59 UTC, geanfarias commented on grails-app/assets/stylesheets/miniAsaasCss/miniAsaas.css
> +    text-align: center;
cria um padrão de espaçamento, ou dois enters ou um enter para separar as linhas... vale a pena colocar um enter na ao abrir uma chave?

2022-03-31 17:12 UTC, geanfarias commented on grails-app/assets/javascripts/miniAsaasJs/miniAsaas.js
> +        let estadoV =  document.querySelector('#estadoCliente').value = data.uf
tu não usa essas variáveis para nada, basta adicionar os valores aos inputs

2022-04-04 18:46 UTC, marlon407 requested changes
A descrião do PR não diz o que o PR está fazendo.

2022-04-04 18:46 UTC, marlon407 commented on grails-app/assets/stylesheets/miniAsaasCss/miniAsaas.css
> +#cadastroCliente {
usamos classes para estilização

2022-04-04 18:46 UTC, marlon407 commented on grails-app/views/index.gsp
> +        <form id="listaCadastro">
é uma lista?

2022-04-04 18:46 UTC, marlon407 commented on grails-app/assets/javascripts/miniAsaasJs/miniAsaas.js
> +    return {
Não pode serializar o form? Dessa forma, se algum campo for adicionar, não precisa alterar essa função.

2022-04-04 18:46 UTC, marlon407 commented on grails-app/assets/javascripts/miniAsaasJs/miniAsaas.js
> +    return {
https://stackoverflow.com/questions/11661187/form-serialize-javascript-no-framework

2022-04-04 18:46 UTC, marlon407 commented on readme.md
> +![miniAsaas](https://user-images.githubusercontent.com/101358660/160670462-a277b04f-47b2-43b5-9a4f-199101edb8b9.gif)
O GIF era só pra descrição do PR. Não precisa ficar dentro do projeto.

2022-04-05 12:31 UTC, devJoseOtavio commented on grails-app/views/index.gsp
> +        <form id="listaCadastro">
Sim e utilizei a identificação como lista pois é atribuído os dados do cliente e a partir disto temos as informações necessárias para o cadastro, como uma coleção ordenada de valores.

2022-04-07 16:56 UTC, marlon407 commented on grails-app/views/index.gsp
> +        <form id="listaCadastro">
Isso é um formulário, e não uma lista de clientes/cadastros.

2022-04-07 16:59 UTC, marlon407 commented
> alteraçoes para resetar pagina
Título do PR continua sem sentido

2022-04-08 13:09 UTC, geanfarias commented on grails-app/assets/javascripts/miniAsaasJs/miniAsaas.js
> +    const valueEstado = document.querySelector('#estadoCliente').value
essas variáveis não estão sendo usadas em outro momento 👀

2022-04-08 13:13 UTC, geanfarias commented on grails-app/assets/javascripts/miniAsaasJs/miniAsaas.js
> +    const cepV = document.getElementById('cepCliente').value
evitar uso de const dentro de função
também nomeia a variável com um nome que faça mais sentido

2022-04-08 19:05 UTC, geanfarias commented on grails-app/assets/javascripts/miniAsaasJs/miniAsaas.js
> +    document.querySelector('#estadoCliente').value
não precisa dessse trecho

2022-04-11 20:40 UTC, lucasJoseMachado approved these changes

2022-04-12 13:17 UTC, merged